name: Publish

on:
  push:
    branches: ["master"]

jobs:
  build:
    uses: UzmaSabir/actions/.github/workflows/npm-docker-push.yaml@main
    permissions:
      contents: read
      id-token: write
      packages: write
      attestations: write
    with:
      node-version: "20"