name: Build

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-source:
    uses: UzmaSabir/actions/.github/workflows/npm-build.yaml@main

    with:
      node-version: "20"
