# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  push:
    branches: [  ]
  pull_request:
    branches: [  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1
      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 21
      - name: Dependency caching
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: ~/.npm
          key: v1-${{ runner.os }}-build-${{ hashFiles ('**/package-lock.json')}}
          restore-keys: |
            v1-${{ runner.os }}-build-
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Update Browserslist DB
        run: npx update-browserslist-db@latest
      - name: Build
        run: CI=false npm run build       

  analyze:
    name: Analyze
    runs-on: [ubuntu-latest]
    permissions:
      security-events: write
      
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'javascript'

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript"

